- name: Check if keystore and trustore files exist
  stat:
    path: "{{ STORE_PATH }}/{{ item }}"
  register: file_stat
  with_items:
    - "{{ KEYSTORE_NAME }}.jks"
    - "{{ TRUSTORE_NAME }}.jks"
    - "/root/.ansible/roles/ansible-role-nifi/tasks/certificate-export-script.sh"
  vars:
    KEYSTORE_NAME: "{{ keystore_name }}"
    TRUSTORE_NAME: "{{ trustore_name }}"
    STORE_PATH: "{{ store_path }}"
  tags:
    - keystore
- name: Export certificate and create keystore if files do not exist
  shell: "bash /root/.ansible/roles/ansible-role-nifi/tasks/certificate-export-script.sh"
  environment:
    REGION: "{{ aws_region }}"
    KEYSTORE_NAME: "{{ keystore_name }}"
    TRUSTORE_NAME: "{{ trustore_name }}"
    STORE_PATH: "{{ store_path }}"
    DOMAIN_NAME: "{{ domain_name }}"
    CERTIFICATE_ARN: "{{ certificate_arn }}"
    VAULT_ADDR: "{{ vault_address }}"
    VAULT_ROLE_NAME: "{{ vault_role_name  }}"
    PATH_KEYSTORE_PASSWORD: "{{ path_keystore_password }}"
    PATH_TRUSTORE_PASSWORD: "{{ path_trustore_password }}"
    PATH_PASSPHRASE_PASSWORD: "{{ path_passphrase_password }}"
  when: not file_stat.results[0].stat.exists or not file_stat.results[1].stat.exists
  tags:
    - keystore
